name: Build (Lualatex)

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_latex:
    name: Build and log errors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Echo cv-marcoduinkerken-ga-build.tex
        run: echo "::debug::Writing '\def\releasenumber{ga-build}\input{cv}' to cv-marcoduinkerken-ga-build.tex"
      - name: Create cv-marcoduinkerken-ga-build.tex
        uses: finnp/create-file-action@2.0.0
        env:
          FILE_NAME: "cv-marcoduinkerken-ga-build.tex"
          FILE_DATA: '\def\releasenumber{ga-build}\input{cv}'
#      - name: LaTeX linter (chktex)
#        uses: j2kun/chktex-action@1.0.3
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint LaTeX document
        uses: ChiefGokhlayeh/textidote-action@v5.3.1
        id: lint
        with:
            root_file: cv-marcoduinkerken-ga-build.tex
      - name: Upload TeXtidote report
        uses: actions/upload-artifact@v3
        with:
            name: textidote_report
            path: report.html
#      - name: Throw error if linter warnings exist
#        if: ${{ steps.lint.outputs.num_warnings != 0 }}
#        run: 'echo "::error file=main.tex::num_warnings: ${{ steps.lint.outputs.num_warnings }}"; exit 1;'
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv-marcoduinkerken-ga-build.tex
          latexmk_use_lualatex: true
      - name: Upload pdf
        uses: actions/upload-artifact@v3
        with:
          path: cv-marcoduinkerken-ga-build.pdf
          if-no-files-found: error
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          path: cv-marcoduinkerken-ga-build.log